# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vPlanGUI_v012.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2175, 2064)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.mainLayout.setObjectName("mainLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(4)
        self.label_3.setMidLineWidth(0)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.line = QtWidgets.QFrame(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 9, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 7, 1, 1)
        self.roomX = QtWidgets.QSpinBox(self.centralWidget)
        self.roomX.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.roomX.setFont(font)
        self.roomX.setObjectName("roomX")
        self.gridLayout_2.addWidget(self.roomX, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setEnabled(True)
        self.label_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.roomZ = QtWidgets.QSpinBox(self.centralWidget)
        self.roomZ.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.roomZ.setFont(font)
        self.roomZ.setObjectName("roomZ")
        self.gridLayout_2.addWidget(self.roomZ, 0, 10, 1, 1)
        self.setWallDims = QtWidgets.QPushButton(self.centralWidget)
        self.setWallDims.setMinimumSize(QtCore.QSize(150, 0))
        self.setWallDims.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.setWallDims.setFont(font)
        self.setWallDims.setObjectName("setWallDims")
        self.gridLayout_2.addWidget(self.setWallDims, 0, 11, 1, 1)
        self.roomY = QtWidgets.QSpinBox(self.centralWidget)
        self.roomY.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.roomY.setFont(font)
        self.roomY.setObjectName("roomY")
        self.gridLayout_2.addWidget(self.roomY, 0, 8, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line_9 = QtWidgets.QFrame(self.centralWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_2.addWidget(self.line_9)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.wallParallel2X_W = QtWidgets.QSpinBox(self.centralWidget)
        self.wallParallel2X_W.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wallParallel2X_W.setFont(font)
        self.wallParallel2X_W.setObjectName("wallParallel2X_W")
        self.gridLayout_3.addWidget(self.wallParallel2X_W, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 8, 1, 1)
        self.wallParallel2X_H = QtWidgets.QSpinBox(self.centralWidget)
        self.wallParallel2X_H.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wallParallel2X_H.setFont(font)
        self.wallParallel2X_H.setObjectName("wallParallel2X_H")
        self.gridLayout_3.addWidget(self.wallParallel2X_H, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setEnabled(True)
        self.label_9.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.setInWalls2X = QtWidgets.QPushButton(self.centralWidget)
        self.setInWalls2X.setMinimumSize(QtCore.QSize(150, 0))
        self.setInWalls2X.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.setInWalls2X.setFont(font)
        self.setInWalls2X.setObjectName("setInWalls2X")
        self.gridLayout_3.addWidget(self.setInWalls2X, 0, 11, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.wallParallel2X_D = QtWidgets.QSpinBox(self.centralWidget)
        self.wallParallel2X_D.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wallParallel2X_D.setFont(font)
        self.wallParallel2X_D.setObjectName("wallParallel2X_D")
        self.gridLayout_3.addWidget(self.wallParallel2X_D, 0, 9, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.line_10 = QtWidgets.QFrame(self.centralWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_2.addWidget(self.line_10)
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.grid4perpedicular = QtWidgets.QGridLayout()
        self.grid4perpedicular.setObjectName("grid4perpedicular")
        self.wallParallel2Z_W = QtWidgets.QSpinBox(self.centralWidget)
        self.wallParallel2Z_W.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.wallParallel2Z_W.setFont(font)
        self.wallParallel2Z_W.setObjectName("wallParallel2Z_W")
        self.grid4perpedicular.addWidget(self.wallParallel2Z_W, 0, 1, 1, 1)
        self.wallParallel2Z_D = QtWidgets.QSpinBox(self.centralWidget)
        self.wallParallel2Z_D.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.wallParallel2Z_D.setFont(font)
        self.wallParallel2Z_D.setObjectName("wallParallel2Z_D")
        self.grid4perpedicular.addWidget(self.wallParallel2Z_D, 0, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_13.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.grid4perpedicular.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralWidget)
        self.label_16.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.grid4perpedicular.addWidget(self.label_16, 0, 3, 1, 1)
        self.setInWalls2Z = QtWidgets.QPushButton(self.centralWidget)
        self.setInWalls2Z.setMinimumSize(QtCore.QSize(150, 0))
        self.setInWalls2Z.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.setInWalls2Z.setFont(font)
        self.setInWalls2Z.setObjectName("setInWalls2Z")
        self.grid4perpedicular.addWidget(self.setInWalls2Z, 0, 10, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        self.label_14.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.grid4perpedicular.addWidget(self.label_14, 0, 5, 1, 1)
        self.wallParallel2Z_H = QtWidgets.QSpinBox(self.centralWidget)
        self.wallParallel2Z_H.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.wallParallel2Z_H.setFont(font)
        self.wallParallel2Z_H.setObjectName("wallParallel2Z_H")
        self.grid4perpedicular.addWidget(self.wallParallel2Z_H, 0, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.grid4perpedicular)
        self.line_11 = QtWidgets.QFrame(self.centralWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_2.addWidget(self.line_11)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setVerticalSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.viewSide = QtWidgets.QRadioButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.viewSide.setFont(font)
        self.viewSide.setObjectName("viewSide")
        self.gridLayout_4.addWidget(self.viewSide, 2, 1, 1, 1)
        self.floor = QtWidgets.QCheckBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.floor.setFont(font)
        self.floor.setChecked(True)
        self.floor.setObjectName("floor")
        self.gridLayout_4.addWidget(self.floor, 3, 0, 1, 1)
        self.grid = QtWidgets.QCheckBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.grid.setFont(font)
        self.grid.setObjectName("grid")
        self.gridLayout_4.addWidget(self.grid, 1, 0, 1, 1)
        self.axis = QtWidgets.QCheckBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.axis.setFont(font)
        self.axis.setObjectName("axis")
        self.gridLayout_4.addWidget(self.axis, 0, 0, 1, 1)
        self.showCoords = QtWidgets.QCheckBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.showCoords.setFont(font)
        self.showCoords.setObjectName("showCoords")
        self.gridLayout_4.addWidget(self.showCoords, 2, 0, 1, 1)
        self.viewTop = QtWidgets.QRadioButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.viewTop.setFont(font)
        self.viewTop.setObjectName("viewTop")
        self.gridLayout_4.addWidget(self.viewTop, 1, 1, 1, 1)
        self.viewFront = QtWidgets.QRadioButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.viewFront.setFont(font)
        self.viewFront.setChecked(True)
        self.viewFront.setObjectName("viewFront")
        self.gridLayout_4.addWidget(self.viewFront, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.line_12 = QtWidgets.QFrame(self.centralWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_2.addWidget(self.line_12)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.redoButton = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.redoButton.setFont(font)
        self.redoButton.setObjectName("redoButton")
        self.gridLayout_5.addWidget(self.redoButton, 0, 2, 1, 1)
        self.deleteAll = QtWidgets.QPushButton(self.centralWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.deleteAll.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.deleteAll.setFont(font)
        self.deleteAll.setObjectName("deleteAll")
        self.gridLayout_5.addWidget(self.deleteAll, 2, 0, 1, 1)
        self.deleteGeom = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.deleteGeom.setFont(font)
        self.deleteGeom.setCheckable(True)
        self.deleteGeom.setObjectName("deleteGeom")
        self.gridLayout_5.addWidget(self.deleteGeom, 2, 2, 1, 1)
        self.undoButton = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.undoButton.setFont(font)
        self.undoButton.setObjectName("undoButton")
        self.gridLayout_5.addWidget(self.undoButton, 0, 0, 1, 1)
        self.undoSpinBox = QtWidgets.QSpinBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.undoSpinBox.sizePolicy().hasHeightForWidth())
        self.undoSpinBox.setSizePolicy(sizePolicy)
        self.undoSpinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.undoSpinBox.setFont(font)
        self.undoSpinBox.setMinimum(0)
        self.undoSpinBox.setMaximum(20)
        self.undoSpinBox.setProperty("value", 10)
        self.undoSpinBox.setObjectName("undoSpinBox")
        self.gridLayout_5.addWidget(self.undoSpinBox, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_22 = QtWidgets.QLabel(self.centralWidget)
        self.label_22.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralWidget)
        self.label_21.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 0, 2, 1, 1)
        self.saveObstacle = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveObstacle.setFont(font)
        self.saveObstacle.setObjectName("saveObstacle")
        self.gridLayout_6.addWidget(self.saveObstacle, 0, 9, 1, 1)
        self.obstacleZ = QtWidgets.QSpinBox(self.centralWidget)
        self.obstacleZ.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.obstacleZ.setFont(font)
        self.obstacleZ.setObjectName("obstacleZ")
        self.gridLayout_6.addWidget(self.obstacleZ, 0, 7, 1, 1)
        self.obstacleY = QtWidgets.QSpinBox(self.centralWidget)
        self.obstacleY.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.obstacleY.setFont(font)
        self.obstacleY.setObjectName("obstacleY")
        self.gridLayout_6.addWidget(self.obstacleY, 0, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralWidget)
        self.label_20.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 0, 6, 1, 1)
        self.obstacleX = QtWidgets.QSpinBox(self.centralWidget)
        self.obstacleX.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.obstacleX.setFont(font)
        self.obstacleX.setObjectName("obstacleX")
        self.gridLayout_6.addWidget(self.obstacleX, 0, 3, 1, 1)
        self.setObstacle = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.setObstacle.setFont(font)
        self.setObstacle.setCheckable(True)
        self.setObstacle.setObjectName("setObstacle")
        self.gridLayout_6.addWidget(self.setObstacle, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.line_7 = QtWidgets.QFrame(self.centralWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_28 = QtWidgets.QLabel(self.centralWidget)
        self.label_28.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_9.addWidget(self.label_28, 1, 1, 1, 1)
        self.domainName = QtWidgets.QComboBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.domainName.setFont(font)
        self.domainName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.domainName.setObjectName("domainName")
        self.gridLayout_9.addWidget(self.domainName, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_31 = QtWidgets.QLabel(self.centralWidget)
        self.label_31.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_2.addWidget(self.label_31)
        self.problemName = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.problemName.setFont(font)
        self.problemName.setObjectName("problemName")
        self.horizontalLayout_2.addWidget(self.problemName)
        self.label_32 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_2.addWidget(self.label_32)
        self.elementsNumber = QtWidgets.QSpinBox(self.centralWidget)
        self.elementsNumber.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.elementsNumber.setFont(font)
        self.elementsNumber.setObjectName("elementsNumber")
        self.horizontalLayout_2.addWidget(self.elementsNumber)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_5 = QtWidgets.QFrame(self.centralWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.entryGoalZ = QtWidgets.QSpinBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryGoalZ.sizePolicy().hasHeightForWidth())
        self.entryGoalZ.setSizePolicy(sizePolicy)
        self.entryGoalZ.setMinimumSize(QtCore.QSize(0, 0))
        self.entryGoalZ.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entryGoalZ.setFont(font)
        self.entryGoalZ.setObjectName("entryGoalZ")
        self.gridLayout_7.addWidget(self.entryGoalZ, 0, 6, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(0, 0))
        self.label_15.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 0, 1, 1, 1)
        self.entryGoalX = QtWidgets.QSpinBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryGoalX.sizePolicy().hasHeightForWidth())
        self.entryGoalX.setSizePolicy(sizePolicy)
        self.entryGoalX.setMinimumSize(QtCore.QSize(0, 0))
        self.entryGoalX.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entryGoalX.setFont(font)
        self.entryGoalX.setObjectName("entryGoalX")
        self.gridLayout_7.addWidget(self.entryGoalX, 0, 2, 1, 1)
        self.saveEntryGoal = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveEntryGoal.setFont(font)
        self.saveEntryGoal.setObjectName("saveEntryGoal")
        self.gridLayout_7.addWidget(self.saveEntryGoal, 0, 9, 1, 1)
        self.entryGoalAngle = QtWidgets.QSpinBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryGoalAngle.sizePolicy().hasHeightForWidth())
        self.entryGoalAngle.setSizePolicy(sizePolicy)
        self.entryGoalAngle.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entryGoalAngle.setFont(font)
        self.entryGoalAngle.setMaximum(450)
        self.entryGoalAngle.setSingleStep(90)
        self.entryGoalAngle.setObjectName("entryGoalAngle")
        self.gridLayout_7.addWidget(self.entryGoalAngle, 0, 8, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(0, 0))
        self.label_23.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 0, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_7.addWidget(self.label_29, 0, 7, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(0, 0))
        self.label_24.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 0, 5, 1, 1)
        self.entryGoalY = QtWidgets.QSpinBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryGoalY.sizePolicy().hasHeightForWidth())
        self.entryGoalY.setSizePolicy(sizePolicy)
        self.entryGoalY.setMinimumSize(QtCore.QSize(0, 0))
        self.entryGoalY.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entryGoalY.setFont(font)
        self.entryGoalY.setObjectName("entryGoalY")
        self.gridLayout_7.addWidget(self.entryGoalY, 0, 4, 1, 1)
        self.planningComboBox = QtWidgets.QComboBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.planningComboBox.setFont(font)
        self.planningComboBox.setObjectName("planningComboBox")
        self.planningComboBox.addItem("")
        self.planningComboBox.addItem("")
        self.planningComboBox.addItem("")
        self.planningComboBox.addItem("")
        self.planningComboBox.addItem("")
        self.gridLayout_7.addWidget(self.planningComboBox, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_7)
        self.line_6 = QtWidgets.QFrame(self.centralWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.previewPDDL = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.previewPDDL.setFont(font)
        self.previewPDDL.setObjectName("previewPDDL")
        self.gridLayout_8.addWidget(self.previewPDDL, 0, 1, 1, 1)
        self.genPDDL = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.genPDDL.setFont(font)
        self.genPDDL.setObjectName("genPDDL")
        self.gridLayout_8.addWidget(self.genPDDL, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        self.line_8 = QtWidgets.QFrame(self.centralWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_2.addWidget(self.line_8)
        self.label_30 = QtWidgets.QLabel(self.centralWidget)
        self.label_30.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_2.addWidget(self.label_30)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.stepForwardSim = QtWidgets.QPushButton(self.centralWidget)
        self.stepForwardSim.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/media-step-forward-64.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.stepForwardSim.setIcon(icon)
        self.stepForwardSim.setObjectName("stepForwardSim")
        self.gridLayout_10.addWidget(self.stepForwardSim, 0, 2, 1, 1)
        self.pauseSim = QtWidgets.QPushButton(self.centralWidget)
        self.pauseSim.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/media-pause-64.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pauseSim.setIcon(icon1)
        self.pauseSim.setObjectName("pauseSim")
        self.gridLayout_10.addWidget(self.pauseSim, 0, 4, 1, 1)
        self.loadSim = QtWidgets.QPushButton(self.centralWidget)
        self.loadSim.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/sinchronize-64.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.loadSim.setIcon(icon2)
        self.loadSim.setObjectName("loadSim")
        self.gridLayout_10.addWidget(self.loadSim, 0, 1, 1, 1)
        self.rewindSim = QtWidgets.QPushButton(self.centralWidget)
        self.rewindSim.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/arrow-69-64.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.rewindSim.setIcon(icon3)
        self.rewindSim.setIconSize(QtCore.QSize(36, 36))
        self.rewindSim.setObjectName("rewindSim")
        self.gridLayout_10.addWidget(self.rewindSim, 0, 5, 1, 1)
        self.playSim = QtWidgets.QPushButton(self.centralWidget)
        self.playSim.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/play-5-64.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.playSim.setIcon(icon4)
        self.playSim.setObjectName("playSim")
        self.gridLayout_10.addWidget(self.playSim, 0, 3, 1, 1)
        self.openPlan = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.openPlan.setFont(font)
        self.openPlan.setObjectName("openPlan")
        self.gridLayout_10.addWidget(self.openPlan, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_10)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.feedbackSim = QtWidgets.QTextEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feedbackSim.sizePolicy().hasHeightForWidth())
        self.feedbackSim.setSizePolicy(sizePolicy)
        self.feedbackSim.setMinimumSize(QtCore.QSize(0, 100))
        self.feedbackSim.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.feedbackSim.setFont(font)
        self.feedbackSim.setLineWidth(1)
        self.feedbackSim.setObjectName("feedbackSim")
        self.gridLayout_12.addWidget(self.feedbackSim, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_12)
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.mainLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.roomX, self.roomY)
        MainWindow.setTabOrder(self.roomY, self.roomZ)
        MainWindow.setTabOrder(self.roomZ, self.setWallDims)
        MainWindow.setTabOrder(self.setWallDims, self.wallParallel2X_W)
        MainWindow.setTabOrder(self.wallParallel2X_W, self.wallParallel2X_H)
        MainWindow.setTabOrder(self.wallParallel2X_H, self.wallParallel2X_D)
        MainWindow.setTabOrder(self.wallParallel2X_D, self.setInWalls2X)
        MainWindow.setTabOrder(self.setInWalls2X, self.wallParallel2Z_W)
        MainWindow.setTabOrder(self.wallParallel2Z_W, self.wallParallel2Z_H)
        MainWindow.setTabOrder(self.wallParallel2Z_H, self.wallParallel2Z_D)
        MainWindow.setTabOrder(self.wallParallel2Z_D, self.setInWalls2Z)
        MainWindow.setTabOrder(self.setInWalls2Z, self.axis)
        MainWindow.setTabOrder(self.axis, self.grid)
        MainWindow.setTabOrder(self.grid, self.showCoords)
        MainWindow.setTabOrder(self.showCoords, self.floor)
        MainWindow.setTabOrder(self.floor, self.viewFront)
        MainWindow.setTabOrder(self.viewFront, self.viewTop)
        MainWindow.setTabOrder(self.viewTop, self.viewSide)
        MainWindow.setTabOrder(self.viewSide, self.deleteAll)
        MainWindow.setTabOrder(self.deleteAll, self.deleteGeom)
        MainWindow.setTabOrder(self.deleteGeom, self.obstacleX)
        MainWindow.setTabOrder(self.obstacleX, self.obstacleY)
        MainWindow.setTabOrder(self.obstacleY, self.obstacleZ)
        MainWindow.setTabOrder(self.obstacleZ, self.entryGoalX)
        MainWindow.setTabOrder(self.entryGoalX, self.entryGoalY)
        MainWindow.setTabOrder(self.entryGoalY, self.entryGoalZ)
        MainWindow.setTabOrder(self.entryGoalZ, self.genPDDL)
        MainWindow.setTabOrder(self.genPDDL, self.previewPDDL)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "vPlainSim v0.1"))
        self.label_3.setText(_translate("MainWindow", "Outside walls"))
        self.label_6.setText(_translate("MainWindow", "Z: Depth"))
        self.label_4.setText(_translate("MainWindow", "Y: Height"))
        self.label_5.setText(_translate("MainWindow", "X: Width"))
        self.setWallDims.setText(_translate("MainWindow", "Set"))
        self.label_7.setText(_translate("MainWindow", "Add parallel to X walls"))
        self.label_10.setText(_translate("MainWindow", "Depth"))
        self.label_9.setText(_translate("MainWindow", "Width"))
        self.setInWalls2X.setText(_translate("MainWindow", "Set"))
        self.label_8.setText(_translate("MainWindow", "Height"))
        self.label_12.setText(_translate("MainWindow", "Add parallel to Z walls"))
        self.label_13.setText(_translate("MainWindow", "Width"))
        self.label_16.setText(_translate("MainWindow", "Height"))
        self.setInWalls2Z.setText(_translate("MainWindow", "Set"))
        self.label_14.setText(_translate("MainWindow", "Depth"))
        self.label.setText(_translate("MainWindow", "Viewing controls"))
        self.viewSide.setText(_translate("MainWindow", "Side view"))
        self.floor.setText(_translate("MainWindow", "Floor"))
        self.grid.setText(_translate("MainWindow", "Grid"))
        self.axis.setText(_translate("MainWindow", "Axis"))
        self.showCoords.setText(_translate("MainWindow", "Show coordinates"))
        self.viewTop.setText(_translate("MainWindow", "Top view"))
        self.viewFront.setText(_translate("MainWindow", "Front view"))
        self.label_2.setText(_translate("MainWindow", "Scene controls"))
        self.redoButton.setText(_translate("MainWindow", "Redo"))
        self.deleteAll.setText(_translate("MainWindow", "Delete scene"))
        self.deleteGeom.setText(_translate("MainWindow", "Delete blocks"))
        self.undoButton.setText(_translate("MainWindow", "Undo"))
        self.label_22.setText(_translate("MainWindow", "Y"))
        self.label_21.setText(_translate("MainWindow", "X"))
        self.saveObstacle.setText(_translate("MainWindow", "Save"))
        self.label_20.setText(_translate("MainWindow", "Z"))
        self.setObstacle.setText(_translate("MainWindow", "Set obstacle"))
        self.label_11.setText(_translate("MainWindow", "Planning controls"))
        self.label_28.setText(_translate("MainWindow", "Domain"))
        self.label_31.setText(_translate("MainWindow", "Problem name"))
        self.label_32.setText(_translate("MainWindow", "Element no (drones)"))
        self.label_15.setText(_translate("MainWindow", "X"))
        self.saveEntryGoal.setText(_translate("MainWindow", "Save"))
        self.label_23.setText(_translate("MainWindow", "Y"))
        self.label_29.setText(_translate("MainWindow", "A"))
        self.label_24.setText(_translate("MainWindow", "Z"))
        self.planningComboBox.setItemText(0, _translate("MainWindow", "Select..."))
        self.planningComboBox.setItemText(1, _translate("MainWindow", "Set goals"))
        self.planningComboBox.setItemText(2, _translate("MainWindow", "Set entries"))
        self.planningComboBox.setItemText(3, _translate("MainWindow", "Set elements"))
        self.planningComboBox.setItemText(4, _translate("MainWindow", "Clear"))
        self.previewPDDL.setText(_translate("MainWindow", "Preview PDDL"))
        self.genPDDL.setText(_translate("MainWindow", "Generate PDDL"))
        self.label_30.setText(_translate("MainWindow", "Simulation controls"))
        self.openPlan.setText(_translate("MainWindow", "Open plan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

